name: LOLIPOP Auto Deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Checkout
        uses: actions/checkout@v3
      - name: Use FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ssh422.lolipop.jp
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/users/1/gloomy.jp-baccho/web/test/
          port: 2222