name: LOLIPOP Auto Deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Checkout
        uses: actions/checkout@v3
      - name: Command Test
        run: |
            echo ${{ secrets.TEST }}
      - name: Use FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./test/
          port: 21
          protocol: ftp